# permissions for end users to view games.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: game-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - games
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - games/status
  verbs:
  - get
